### ISSUE TITLE
For a specific TV show, plugin can search but not download in 12.0.0, and not search at all in 18.0.0

### ISSUE THREAD

**Issue by Percee** [jellyfin/jellyfin-plugin-opensubtitles#102]
Hi,

I tried both jellyfin 10.7 with the opensubtitles plugin 12.0.0 and jellyfin 10.8 with the 18.0.0 plugin.

I have a TV show A for which I can search, find and download subtitles in jellyfin 10.7 and 10.8

I also have a TV show B (Boruto) for which I can search, and:
- in 10.7, find a candidate, but when clicking on download, the download happens (My OpenSubtitles ratio goes down by 1), but then an HttpRequestException is thrown when processing the download.
- in 10.8, for the same episode, the search instantly returns nothing

This happened for all the episodes I tried for this TV show.

Log for sub search failing in 10.8:
[2022-04-08 21:04:00.904 +00:00] [WRN] [8] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://myserv/Items/6b46c49b8bf82d1ab75f12d942aff2f3/RemoteSearch/Subtitles/eng" to "myip" in 0:00:00.9097688 with Status Code 200

Log for sub search succeeding but then error happening during or after download in 10.7:
[2022-04-08 21:13:07.253 +00:00] [WRN] [15] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://myserv/Items/6b46c49b8bf82d1ab75f12d942aff2f3/RemoteSearch/Subtitles/eng" to "myip" in 0:00:02.469229 with Status Code 200
[2022-04-08 21:14:16.975 +00:00] [INF] [25] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Remaining downloads: 16
[2022-04-08 21:14:17.328 +00:00] [ERR] [34] Jellyfin.Api.Controllers.SubtitleController: Error downloading subtitles
System.Net.Http.HttpRequestException: Subtitle with Id 6972559 could not be downloaded: OK
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetSubtitlesInternal(String id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.DownloadSubtitles(Video video, LibraryOptions libraryOptions, String subtitleId, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SubtitleController.DownloadRemoteSubtitles(Guid itemId, String subtitleId)

**Comment by Percee** [comment]
Argh, after going to opensubtitles.com and manually downloading the subtitle for that episode(they show a download like they have it), the .srt is 0kb, just empty.

So it seems the latest plugin detects this and shows an empty search, I guess. Closing this.

**Comment by MBR-0001** [comment]
Correct, the latest version detects empty subtitle files (but doesn't log that "properly" in the logs 🙁)

As for the .ass thing, I read that they (opensubtitles) were running some DB maintenance lately. It is also possible that that subtitle file is just broken or there's an outage right now

I'll ask about it in a few days if the issue persists

**Comment by MBR-0001** [comment]
@Percee `"some weirdly formatted SSA file that the system doesn't recognise... can happen sometimes unfortunately, subtitle is now disabled and won't be fixed."` ([link](https://forum.opensubtitles.org/viewtopic.php?f=8&t=17146&start=90#p47228))

**Comment by Percee** [comment]
> @Percee `"some weirdly formatted SSA file that the system doesn't recognise... can happen sometimes unfortunately, subtitle is now disabled and won't be fixed."` ([link](https://forum.opensubtitles.org/viewtopic.php?f=8&t=17146&start=90#p47228))

Nice catch!
