### ISSUE TITLE
Subtitles aren't downloaded automatically for me.

### ISSUE THREAD

**Issue by sander1095** [jellyfin/jellyfin-plugin-opensubtitles#104]
Hello!

I have set up my plugin, but it doesn't seem to work.

I can run the scheduled task to download missing subtitles, but nothing happens. The OS API overview also says no downloads occurred. 
WHen I go to the show I downloaded (Which is identified by Jellyfin correctly), the subtitles show "off". When I click on edit -> find subtitles, some do appear.. but this is only after I messed around with the plugin, created an new API consumer, connected it to my plugin, deleted the plugin, reinstalled the plugin and reconfigured it.. 

I am still expecting it to automatically download subtitles, though..

Could anyone help me out? Or point me in the direction of the logs? I am running jellyfin on a raspberry pi 3b+

**Comment by MBR-0001** [comment]
The easiest way to approach this would be to check the logs, you can find them in the "Logs" section of the "Advanced" category in the server administration page (should be just above plugins & scheduled tasks). Look for lines containing `opensubtitles`, if there are exceptions (errors) please report them here so I can look into it :)

Another thing worth checking is whether the `Only download subtitles that are a perfect match for my video files` option is turned on in the settings of your libraries, if that option is turned on the plugin will only download subtitles that match your files _perfectly_ (subtitles made for that exact version of the movie/episode, it does that by computing a hash of the file)

**Comment by MBR-0001** [comment]
The `Download missing subtitles` task ended quite quickly (`Completed after 0 minute(s) and 0 seconds`), how many items do you have in your library and which version of jellyfin and the plugin are you using?

As for logs, I am not sure why they would be missing, for me they are found in `/var/lib/jellyfin/log/` but they should also be listed in the Logs section in the dashboard - clicking on an entry _should_ open the full log in a new tab.

I also suggest enabling [debug logging](https://jellyfin.org/docs/general/administration/troubleshooting.html#debug-logging), running the subtitle download task and then checking the logs (or running `journalctl -u jellyfin -f`)

**Comment by sander1095** [comment]
Running `tree . | tail -1` in my ` media` folder reports 1716 files, possibly some being subtitle files and stuff.

I use Jellyfin version 10.7.7  and OpenSubtitles 12.0.0.0.

Going to the logs section in the dsahboard results in an empty screen; the JSON response also only returns an empty array.

I will try the debug logging as well. I am posting this comment now because my laptop is almost out of battery;  I will edit with debug logging results!

**Comment by MBR-0001** [comment]
Yeah it seems like the plugin is working correctly :thinking:

One way to check if debug logging is properly enabled is to do manual subtitle searches and look for lines like
```
[00:53:16] [DBG] [31] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Search query: {"languages": "en", "moviehash": "8f3c49659fa2e081", "type": "movie", "query": "redacted", "imdb_id": "424600"}
```

If they don't appear something is wrong :confused:

**Comment by MBR-0001** [comment]
Jellyfin 10.8 is now out, which means the plugin can now be updated to the latest version, can you check if this is still happening?

**Comment by gartner2000** [comment]
Hi
I did notice recently that my plugin stopped working in the late of May.
I use JF 10.8.1 and plugin version 18. When I put in my username, passwd and api key. I got OK, I can download 20 in a day.

But it failed somehow. Cant find anything in logs, beside this:
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitlesHandler.OpenSubtitlesRequestHelper.SendRequestAsync(String url, HttpMethod method, Object body, Dictionary`2 headers, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitlesHandler.RequestHandler.SendRequestAsync(String endpoint, HttpMethod method, Object body, Dictionary`2 headers, String apiKey, Int32 attempt, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitlesHandler.OpenSubtitles.SearchSubtitlesAsync(Dictionary`2 options, String apiKey, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)

And on opensubtiltes's site, i can see that 0/20 subtitles is downloaded..

**Comment by MBR-0001** [comment]
> Hi
> I did notice recently that my plugin stopped working in the late of May.
> I use JF 10.8.1 and plugin version 18. When I put in my username, passwd and api key. I got OK, I can download 20 in a day.
> 
> But it failed somehow. Cant find anything in logs, beside this:
>    at Jellyfin.Plugin.OpenSubtitles.OpenSubtitlesHandler.OpenSubtitlesRequestHelper.SendRequestAsync(String url, HttpMethod method, Object body, Dictionary`2 headers, CancellationToken cancellationToken)
>    at Jellyfin.Plugin.OpenSubtitles.OpenSubtitlesHandler.RequestHandler.SendRequestAsync(String endpoint, HttpMethod method, Object body, Dictionary`2 headers, String apiKey, Int32 attempt, CancellationToken cancellationToken)
>    at Jellyfin.Plugin.OpenSubtitles.OpenSubtitlesHandler.OpenSubtitles.SearchSubtitlesAsync(Dictionary`2 options, String apiKey, CancellationToken cancellationToken)
>    at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
> 
> And on opensubtiltes's site, i can see that 0/20 subtitles is downloaded..
> 
> 
> 

The error message is incomplete unfortunately, it's missing the most important part :/

Can you try to obtain more logs? You can manually download a subtitle through the web UI which should produce an error if something is broken.


Might be worth saying that opensubtitles had some issues a few days ago, I too noticed some error messages in my logs but those are expected.

**Comment by gartner2000** [comment]
No more logs than that from a scheduled task was showing...

But I tried a manual search.. it worked.
[2022-07-16 11:19:10.101 -07:00] [INF] [259] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Remaining downloads: 99
[2022-07-16 11:19:10.490 -07:00] [INF] [49] MediaBrowser.Providers.Subtitles.SubtitleManager: Saving subtitles to "/data/movies/Trainspotting 1996/Trainspotting 1996 BluRay x264 720p AC3 - NTR.nor.srt"
[2022-07-16 11:19:10.493 -07:00] [WRN] [84] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https:/xxxxx/Items/503c3e1e2cefcf39464a39c541f5d8f9/RemoteSearch/Subtitles/e02a34f56233e3e5e7765144ca8f184f_srt-nor-202417" to "xx.xxxxxx.xxx" in 0:00:02.6507303 with Status Code 204

But when a scheduled is running, it scans, but find nothing to download.

**Comment by MBR-0001** [comment]
If manual searching and downloading worked then that error must've been caused by an API outage (those happen every once in a while and there's nothing that can be done about it)

As for subtitles not being downloaded, the simple explanation could be that there are no subtitles available for your files (very likely if you have perfect match enabled)

**Comment by abienz** [comment]
I've also found this to be a problem, by investigation shows very little in the way of logs, and I never get results when I search manually, which led me to believe that it was a file-naming issue.

I decided to check the meta data, as in the Discord chat a long time ago someone mentioned that this was used for the searches, everything looked good, but one thing that was missing was the imdb id field, I decided to add that manually by searching for my shows on imdb and copy-pasting from the URL, and then try searching for subtitles again.

Tested on two shows from the same series and another from a different series, and when I manually search I get good results almost instantly!

Is there a way to populate the imdb id in the meta-data automatically, either from Sonarr/Radarr or Jellyfin?

Can this plugin work without that ID?

**Comment by MBR-0001** [comment]
When the IMDb id is missing the filename is sent to the opensubtitles API, searching by filename is obviously not accurate which results in none or poor results :/

As for populating the IMDb id automatically, this should work out of box on any jellyfin installation, you just have to enable it in library settings under metadata downloaders

**Comment by abienz** [comment]
Right that makes sense as my episodes have been renamed by sonarr to follow the Show/Season/EpisodeName convention, maybe I should make it match the Jellyfin convention a little more closely.

Strange that it always came back with no results though.

I checked my settings and I found that I do have metadata scraping enabled, but not for episode level, so I've enabled it now and will see if that works.

**Comment by rwjack** [comment]
> Another thing worth checking is whether the `Only download subtitles that are a perfect match for my video files` option is turned on in the settings of your libraries

Well, those were an intense couple of hours I just wasted on debugging something that actually worked

**Comment by slickwarren** [comment]
Just want to summarize this for anyone else who runs into this problem: 
* ensure you have the opensubtitle plugin installed and authenticated/logged in
* navigate to your administrator dashboard -> libraries
* select the library containing the media you wish to bulk download subtitles for

![Screen Shot 2023-01-05 at 10 22 09 AM](https://user-images.githubusercontent.com/16691014/210853215-e39d477c-6b8b-4c1f-a454-4d65a026f4ec.png)

* scroll down to the `opensubtitles` section, select your language(s) and modify the `perfect match` option to fit your preferences
![Screen Shot 2023-01-05 at 10 22 43 AM](https://user-images.githubusercontent.com/16691014/210853219-f389b733-bdb5-4465-b64c-5862fb230ece.png)

**Comment by monitor22** [comment]
> * select the library containing the media you wish to bulk download subtitles for

After pressing ok, does it automatically download all subtitles?

**Comment by MBR-0001** [comment]
I don't think so, I believe you have to run the "Download missing subtitles" task for it to start

**Comment by slickwarren** [comment]
> > * select the library containing the media you wish to bulk download subtitles for
> 
> After pressing ok, does it automatically download all subtitles?

not immediately, but it should queue and run as part of the scheduled task. You can also manually trigger it as mentioned above.

**Comment by Meravici** [comment]
I had the same issue `Completed after 0 minute(s) and 0 seconds`.

In my case, the problem turned out to be that I did not have subtitle download language specified in the library settings 
<img width="1027" alt="image" src="https://github.com/jellyfin/jellyfin-plugin-opensubtitles/assets/882515/1e882566-51df-4ab3-a427-c87f9f4a84c1">

After ticking `English` and starting `Download missing subtitles` it started working

**Comment by AllegraCodes** [comment]
I had the same problem, I hadn't ticked a language and it just said "Completed after 0 minutes and 0 seconds". Additional logging would be nice.

**Comment by tcurdt** [comment]
On opensubtitles I can see that files are being downloaded - but they are just not stored for me.
Shouldn't they be just next to the videos likes this?

![Screenshot 2024-08-11 at 21 43 25](https://github.com/user-attachments/assets/33b9821e-55a6-4c66-9c7c-1b0722c70b5e)

**Comment by MBR-0001** [comment]
> On opensubtitles I can see that files are being downloaded - but they are just not stored for me. Shouldn't they be just next to the videos likes this?
> 
> ![Screenshot 2024-08-11 at 21 43 25](https://private-user-images.githubusercontent.com/13697/356902194-33b9821e-55a6-4c66-9c7c-1b0722c70b5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MDYyMTgsIm5iZiI6MTcyMzQwNTkxOCwicGF0aCI6Ii8xMzY5Ny8zNTY5MDIxOTQtMzNiOTgyMWUtNTVhNi00YzY2LTljN2MtMWIwNzIyYzcwYjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE5NTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMDY5ZTg2Zjk5NTM4ZTk2NmMxMDdjOGE5Njg3ZGE5MTMwOWY0NjU3MTY5OGVkMTY2NTI0ZmE2NjJiOGRiODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.60A7QEAvhH-SQJa_ejq9IyDPvZz4Ys4t8mspdQ2V0wo)

It should, if it fails (FS permissions?) it stores them in the jellyfin metadata folder

All saving should be logged, successful or not

**Comment by tcurdt** [comment]
> It should, if it fails (FS permissions?) it stores them in the jellyfin metadata folder

Yeah, it's a permission thing and they get stored in `find /config/metadata/ -name "*.srt"`

Thanks for the pointer!

**Comment by tcurdt** [comment]
Is there a way to specify auto download only for certain series?

**Comment by MBR-0001** [comment]
Currently it's library based, that logic is stored in the server so a functionality like that should/could be requested at https://features.jellyfin.org/

**Comment by Silverbullet069** [comment]
> Another thing worth checking is whether the `Only download subtitles that are a perfect match for my video files` option is turned on in the settings of your libraries, if that option is turned on the plugin will only download subtitles that match your files _perfectly_
Thank youuuu. I've been wondering about why my subtitles aren't being downloaded. It's because I have this setting on. Is it on by default? If yes then I think this is not a really good design.

**Comment by MBR-0001** [comment]
@Silverbullet069  This option is turned _on_ by default (at least in 10.9), while it might seem like a good idea to have it off by default in this scenario, it also might result in a library with subtitles that don't match audio/video, which, in my opinion, sounds like unwanted behavior, so a double edged sword...

might be worth starting a feature request on https://features.jellyfin.org

**Comment by Kuphi** [comment]
> [@Kuphi](https://github.com/Kuphi) the value of _limitReset is set to whatever opensubtitles returns, so even if they changed when it resets it should be accurate
> 
> <img alt="Image" width="953" height="109" src="https://private-user-images.githubusercontent.com/55142207/494886007-51e4d2b8-12b9-4527-8a04-92e0a1048ace.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk4NDQ5NzUsIm5iZiI6MTc1OTg0NDY3NSwicGF0aCI6Ii81NTE0MjIwNy80OTQ4ODYwMDctNTFlNGQyYjgtMTJiOS00NTI3LThhMDQtOTJlMGExMDQ4YWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDA3VDEzNDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMDhhM2MwZjRlNmZhYjk3ODk5OTMwOWIwNzc5OTQ0NzljNGM1MjRkMjZhY2UwYTI1NWU3ZjNhNjUzNmFlZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FBz0BC5UopGLORqjUuJRUfRnIDUEJDt6cBbISZKyhxc">

I think it doesn't work as it should. The plugin is not working for me, unless I start manual subtitle downloads and then the automatic one. Today I again got:
[2025-10-07 15:41:53.474 +02:00] [INF] Daily download limit reached, returning no results for automated task
while opensubtitles.com shows:

<img width="1282" height="119" alt="Image" src="https://github.com/user-attachments/assets/aacdfc5d-a43a-46fa-83e0-33259ab1c11a" />
