### ISSUE TITLE
Open Subtitles 18.0.0.0.0 - Status: Malfunctioned

### ISSUE THREAD

**Issue by PCGoHome** [jellyfin/jellyfin-plugin-opensubtitles#114]
Can't quite figure out how to get this plugin to work.  It wasn't working for versions 10.8.7 nor 10.8.8 and still isn't working after updating to the latest release of Jellyfin 10.8.9.

This is what it shows on my plugin dashboard.  Open Subtitles 18.0.0.0.0 - Status: Malfunctioned
![Screen Shot 2023-01-23 at 11 36 40 AM](https://user-images.githubusercontent.com/123412111/214133182-3cb843ad-2c33-4dd8-b19a-60aaa70a01a8.png)

I noticed there is a scheduled task called "Download Missing Subtitles" that runs every 24 hours but I don't have any new subtitles for my media.  

I am running on a hackintosh on MacOS 10.15.7.  I have other plugins that I've installed that work fine.  

This is an excerpt from my log files showing where errors begin with the plugin.  It repeats a couple times with the same .dll file errors: 

`[2023-01-23 11:01:10.149 -08:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/msdia140.dll". Unknown exception was thrown. Disabling plugin.
System.BadImageFormatException: Bad IL format. The format of the file '/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/msdia140.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[2023-01-23 11:01:10.160 -08:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/vcruntime140.dll". Unknown exception was thrown. Disabling plugin.
System.BadImageFormatException: Bad IL format. The format of the file '/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/vcruntime140.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[2023-01-23 11:01:10.161 -08:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/codecoveragemessages.dll". Unknown exception was thrown. Disabling plugin.
System.BadImageFormatException: Bad IL format. The format of the file '/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/codecoveragemessages.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[2023-01-23 11:01:10.161 -08:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/msvcp140_atomic_wait.dll". Unknown exception was thrown. Disabling plugin.
System.BadImageFormatException: Bad IL format. The format of the file '/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/msvcp140_atomic_wait.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[2023-01-23 11:01:10.162 -08:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/msvcp140.dll". Unknown exception was thrown. Disabling plugin.
System.BadImageFormatException: Bad IL format. The format of the file '/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/msvcp140.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[2023-01-23 11:01:10.163 -08:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/msvcdis140.dll". Unknown exception was thrown. Disabling plugin.
System.BadImageFormatException: Bad IL format. The format of the file '/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/msvcdis140.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[2023-01-23 11:01:10.164 -08:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/covrun32.dll". Unknown exception was thrown. Disabling plugin.
System.BadImageFormatException: Bad IL format. The format of the file '/Users/USER/.local/share/jellyfin/plugins/opensubtitles/bin/CodeCoverage/covrun32.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
`

**Comment by MBR-0001** [comment]
did you install the plugin through the server UI?
Some of these paths look very unfamiliar to me, for me the plugins folder has a `Open Subtitles_18.0.0.0` folder with `Jellyfin.Plugin.OpenSubtitles.dll  jellyfin-plugin-opensubtitles.png  meta.json` in it

**Comment by PCGoHome** [comment]
hmmm, in my `plugins/opensubtitles` folder I just had the `bin` folder from the original `dotnet publish --configuration Release --output bin` command, and the `meta.json file.`

I ended up moving the `Jellyfin.Plugin.OpenSubtitles.dll` and  `jellyfin-plugin-opensubtitles.png` from the `bin` folder to the `opensubtitles` folder, deleted the `bin` folder, and now it seems to work...  

Thanks!
