### ISSUE TITLE
Can't save authentication credentials

### ISSUE THREAD

**Issue by psiwray** [jellyfin/jellyfin-plugin-opensubtitles#123]
I'm running the latest Docker image locally built. All working so far, but when I installed the Open Subtitles plugin, I can't save the authentication credentials because:

```
[11:24:30] [ERR] [22] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Jellyfin.Plugin.OpenSubtitles/ValidateLoginInfo.
System.InvalidOperationException: The AuthorizationPolicy named: 'DefaultAuthorization' was not found.
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData, IEnumerable`1 policies)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

Tried most of the suggestions found on other relevant issues but nothing is working so far. Also (I don't know if this is because there's no valid login configuration or something else) I can't see the UI elements like the subtitles section in the library configuration.

The Jellyfin version is 10.9.0.

**Comment by MBR-0001** [comment]
Plugin has not been updated yet to work on 10.9, I started working on that in https://github.com/jellyfin/jellyfin-plugin-opensubtitles/pull/115 but I'm waiting for 10.9 beta to come out

**Comment by psiwray** [comment]
Okay, good to know, thank you!
