### ISSUE TITLE
Subtitle download fails

### ISSUE THREAD

**Issue by VortrexFTW** [jellyfin/jellyfin-plugin-opensubtitles#126]
Searching for subtitles works great, but it fails when I select one to download. Jellyfin front-end in the browser shows a notification saying download is queued, but subtitle is never downloaded.

**Server and plugin info:**
Jellyfin server 10.7.7 on Windows 10 x64, using Opensubtitles plugin 12.0.0.0. Login is correct and API key present.

**Details from log:**
```
[2023-06-17 20:07:53.959 -05:00] [ERR] [77] Jellyfin.Api.Controllers.SubtitleController: Error downloading subtitles
System.FormatException: The string '2023-06-18 23:59:59Z ts=1687050473' was not recognized as a valid DateTime. There is an unknown word starting at index '21'.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s, IFormatProvider provider, DateTimeStyles styles)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetSubtitlesInternal(String id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.DownloadSubtitles(Video video, LibraryOptions libraryOptions, String subtitleId, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SubtitleController.DownloadRemoteSubtitles(Guid itemId, String subtitleId)
```

**Comment by crobibero** [comment]
10.7.7 is not a supported Jellyfin version. If this still happens with the latest plug-in version + Jellyfin version, please create a new issue.

**Comment by VortrexFTW** [comment]
Ah I must've missed that, thank you for the prompt reply!
