### ISSUE TITLE
Unable to sign into the opensubtitles plugin

### ISSUE THREAD

**Issue by pd98** [jellyfin/jellyfin-plugin-opensubtitles#131]
Hi,

I am trying to put in my credentials for the opensubtitles plugin, however the screen just keeps loading.

I think there is some ambiguity on whether to use .com or .org - however .com is not reachable and is producing 500 status code when i check the logs in jellyfin

**Comment by MBR-0001** [comment]
I cannot reproduce the issue, login works fine for me

There's a chance opensubtitles had an outage, can you check if the issue is still happening and maybe post the error logs?

To log in you need to use .com credentials, also, what is the version of the plugin you are using?

**Comment by kikmak42** [comment]
I have similar issue, I accidentally open the issue in the main repo : https://github.com/jellyfin/jellyfin/issues/10064

I have attached the details and log in there.

I checked wget is working for both www.opensubtitles.org and www.opensubtitles.com from my container/device.

**Comment by pd98** [comment]
@MBR-0001 - Please check the details provided by @kikmak42 - I am facing the same issue.

**Comment by AmbulantRex** [comment]
I'm also having the same problem. Here is a stack trace:
```bash
[2023-08-13 21:06:18.191 +00:00] [ERR] [15] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Jellyfin.Plugin.OpenSubtitles/ValidateLoginInfo".
System.InvalidOperationException: The AuthorizationPolicy named: 'DefaultAuthorization' was not found.
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData, IEnumerable`1 policies)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

I believe this is the commit that affected it:
https://github.com/jellyfin/jellyfin/commit/209edd38a4163a8cf4abd5e47bfe0ea1a100f351

And this appears to be the line in yours that is squawking about it:
https://github.com/jellyfin/jellyfin-plugin-opensubtitles/blob/f7b631c6efe94c176b978068b473b8d5b90e1438/Jellyfin.Plugin.OpenSubtitles/API/OpenSubtitlesController.cs#L18

I am using version 10.8.10 currently and it probably works fine on older versions.

**Comment by gartner2000** [comment]
I got this error:
[23:19:14] [ERR] [56] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Invalid response: ServiceUnavailable - <!DOCTYPE html>
<html>
  <head>
    <title>503 Backend fetch failed</title>
  </head>
  <body>
    <h1>Error 503 Backend fetch failed</h1>
    <p>Backend fetch failed</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 1880097160</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

**Comment by MBR-0001** [comment]
That's an error caused by an outage at opensubtitles, can't really do much about it

**Comment by WoxWik** [comment]
Open subtitles Stopped working for me not sure why. Getting the spinning load if I try to readd my credentials

**Comment by crobibero** [comment]
> Open subtitles Stopped working for me not sure why. Getting the spinning load if I try to readd my credentials 

Please add server logs.

**Comment by r6d2** [comment]
> I got this error: [23:19:14] [ERR] [56] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Invalid response: ServiceUnavailable -
> 
> <title>503 Backend fetch failed</title>
> # Error 503 Backend fetch failed
> Backend fetch failed
> 
> ### Guru Meditation:
> XID: 1880097160
> 
> Varnish cache server

Getting the same issue here. Does it work for you now?

**Comment by opensubtitles** [comment]
GURU mediation, error 503 is error on our side, when servers are overloaded. We have hard time to scale this, everything cost money, we are running mostly free service, so our uptime is not 100%

Response on this is: try again later it is server error.
