### ISSUE TITLE
Can't download subtitles

### ISSUE THREAD

**Issue by TungstenIodide** [jellyfin/jellyfin-plugin-opensubtitles#134]
When trying to download subtitles, I get `download limit reached` error. 

I didn't download any subtitles today, and I am the only user of my server.

Changing log level to informational did not provide any additional information.

Jellyfin version: 10.8.10
Open Subtitles: 19.0.0.0

```
[17:57:16] [INF] [10] System.Net.Http.HttpClient.Default.LogicalHandler: End processing HTTP request after 18.0601ms - 200
[17:57:16] [WRN] [22] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://mediacenter.lan/Items/96607eff381f7f7293bb162bcdbeff64/RemoteSearch/Subtitles/eng to 192.168.1.99 in 0:00:01.7671933 with Status Code 200
[17:57:20] [ERR] [24] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: OpenSubtitles download limit reached
[17:57:20] [ERR] [24] Jellyfin.Api.Controllers.SubtitleController: Error downloading subtitles
MediaBrowser.Common.Extensions.RateLimitExceededException: OpenSubtitles download limit reached
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetSubtitlesInternal(String id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.DownloadSubtitles(Video video, LibraryOptions libraryOptions, String subtitleId, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SubtitleController.DownloadRemoteSubtitles(Guid itemId, String subtitleId)
```

**Comment by TungstenIodide** [comment]
That seems to be a common issue with OpenSubtitles. In the profile page, they have a button `If your download limit is wrong, click here to fix it`. After clicking it, it works!
