### ISSUE TITLE
[BUG]: Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request.

### ISSUE THREAD

**Issue by jiriks74** [jellyfin/jellyfin-plugin-opensubtitles#142]
The plugin doesn't let me sign in. All I get in the UI is an endless spinner (loading animation).
While looking into logs I noticed an error

### Environment
OS: Docker
Jellyfin version: `10.9.0`
Plugin version: `19.0.0.0`
Host: Raspberry Pi 5
RAM: 8GB
Storage:
  - Docker - SSD
  - Media  - HDD

<details>
<summary>Log</summary>

```
[02:55:57] [ERR] [81] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Jellyfin.Plugin.OpenSubtitles/ValidateLoginInfo.

System.InvalidOperationException: The AuthorizationPolicy named: 'DefaultAuthorization' was not found.

   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData, IEnumerable`1 policies)

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)

   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)

   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)

   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)

   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)

   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)

   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

</details>

Here's what the UI looks like:
![image](https://github.com/jellyfin/jellyfin-plugin-opensubtitles/assets/54378412/4185f825-a0f3-428c-ba56-5bded779e8f8)

### Solutions I tried

1. Logging in again
2. Restarting Jellyfin
3. Reinstalling the plugin
4. Checking if the API is up
5. Deleting all Jellyfin configuration data and installing it again
6. Inputting my own API key
7. Changing my password (as mentioned in [this comment](https://github.com/jellyfin/jellyfin-plugin-opensubtitles/issues/109#issuecomment-1328270619))

**Comment by crobibero** [comment]
Jellyfin 10.9 is not supported yet.

**Comment by jiriks74** [comment]
Is there a way to allow plugin installation for only a specific version of Jellyfin? The plugin being displayed in the repo implies that it's working. If this is not possible I think that it's something to consult with Jellyfin - I'd make an issue for it. 

Would be way better UX.

**Comment by crobibero** [comment]
No, that is not a feature Jellyfin has.

**Comment by Simsala91** [comment]
This is still happening in 19.2403.7.0, which is supposed to work with 10.9 as far as I understand?

**Comment by crobibero** [comment]
Yes, the unstable plugin should work with unstable server. If it is not please create a new issue.

**Comment by jiriks74** [comment]
@Simsala91 Your issue is probably resolved in #115.

Build yourself the plugin if you need the plugin now or wait some time until #115 is merged and published to the unstable repository.

**Comment by Simsala91** [comment]
@jiriks74 Thanks for the response, mostly wanted to make sure everything is working as expected once 10.9.0 actually releases :)

**Comment by jiriks74** [comment]
> @jiriks74 Thanks for the response, mostly wanted to make sure everything is working as expected once 10.9.0 actually releases :)

I get that. Sadly I have to use 10.9 since 10.8 has quite some issues with my RPi5 which 10.9 doesn't. Like scrubbing through the film, it takes a longer time until the film loads, the transcoding is slower...

Some of the issues may be related to the docker image as 10.9 has probably newer dependencies with better support for 10.9
