### ISSUE TITLE
Error downloading subtitles

### ISSUE THREAD

**Issue by diegodlh** [jellyfin/jellyfin-plugin-opensubtitles#15]
I am using version 6 of the Open Subtitles plugin and I am getting the same error message that was reported on (closed) [bug #1424](https://github.com/jellyfin/jellyfin/issues/1424) of the jellyfin repository:
`[2019-10-25 18:38:12.594 -03:00] [ERR] Error downloading subtitles from "Open Subtitles"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()
`
This error message is triggered both when (i) I run the scheduled task to download subtitles, or (ii) I search for subtitles in a particular movie.
I tried with version 5 as well, and same error appears (after restarting the server). I also tried with and without username and password (it is hard to tell if my user and pass are being saved, because the fields are reset to blank after clicking "save" in the plugin settings).
The error appears if I request subtitle download both from Firefox browser, and from the Android app.

**Comment by anthonylavado** [comment]
@diegodlh Have you tried with version 7 on the latest 10.4.2?

**Comment by gabri94** [comment]
I have a very similar problem for the version 7 on 10.4.3
This is the error message i get while trying the download
```
 [ERR] Error downloading subtitles
   at MediaBrowser.Providers.Subtitles.SubtitleManager.DownloadSubtitles(Video video, LibraryOptions libraryOptions, String subtitleId, CancellationToken cancellationToken)

```

**Comment by gabri94** [comment]
I enabled the logging and this is the full error trace:
```
MediaBrowser.Common.Extensions.RateLimitExceededException: OpenSubtitles rate limit reached
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetSubtitlesInternal(String id, PluginConfiguration options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.DownloadSubtitles(Video video, LibraryOptions libraryOptions, String subtitleId, CancellationToken cancellationToken)
   at MediaBrowser.Api.Subtitles.SubtitleService.<>c__DisplayClass14_0.<<Post>b__0>d.MoveNext()
```
Since I haven't downloaded any subtitles today i created a new account to have an additional confirmation and i got the same error with the new account.

**Comment by anthonylavado** [comment]
@gabri94 Just had a chance to look at this. OpenSubtitles limits by IP address, not by account, so changing accounts won’t get past it.

**Comment by anthonylavado** [comment]
We’ll try to look at enabling better throttling protection in the plug-in, but ultimately the error is outside of our control.

**Comment by pmorch** [comment]
Is this a duplicate of #63 and fixed by #83?
