### ISSUE TITLE
language settings

### ISSUE THREAD

**Issue by erlendoyen** [jellyfin/jellyfin-plugin-opensubtitles#151]
Hi

i have attempted to change all settings related to subtitle language to English every where in jellyfin

but from the logfile, the plugin still attempts to download unsupported language, where is this setting stored?

```
System.NotSupportedException: Language 'nb' is not supported
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetLanguage(String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2024-09-19 00:21:42.523 +02:00] [ERR] [47] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from "Open Subtitles"
System.NotSupportedException: Language 'nb' is not supported
```

**Comment by crobibero** [comment]
Have you also changed the language under Library -> Subtitle Downloads -> Download languages?

**Comment by erlendoyen** [comment]
Yes I have. 

Is this message generated for all files individually? In that case is it possible to log what files the errors are logged for.

I know that open subtitles got files for some recently added files, but the subs are not downloaded

**Comment by MBR-0001** [comment]
Are you uh sure that the "Norwegian Bokmål" language is not checked by accident? "nb" is the code for it

Not sure how else this could happen

**Comment by erlendoyen** [comment]
turns out that it was still selected for some libraries, it would be nice to output the library or file names in the log.
