### ISSUE TITLE
Error downloading subtitles

### ISSUE THREAD

**Issue by earder** [jellyfin/jellyfin-plugin-opensubtitles#153]
The subtitle plugin works fine when I manually download a subtitles for in jellyfin.
However when I run it as a scheduled task it fails with this error:

[2024-09-22 18:43:18.808 +00:00] [ERR] [101] MediaBrowser.Providers.MediaInfo.SubtitleScheduledTask: Error downloading subtitles
System.Net.Http.HttpRequestException: Subtitle with Id 393772 could not be downloaded: OK
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetSubtitlesInternal(String id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.DownloadSubtitles(Video video, LibraryOptions libraryOptions, String subtitleId, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.SubtitleDownloader.DownloadSubtitles(Video video, List1 mediaStreams, Boolean skipIfEmbeddedSubtitlesPresent, Boolean skipIfAudioTrackMatches, Boolean requirePerfectMatch, String language, String[] disabledSubtitleFetchers, String[] subtitleFetcherOrder, VideoContentType mediaType, Boolean isAutomated, CancellationToken cancellationToken)

The problem keeps returning and only started a few days ago. Before then it worked fine.

Also, I have searched the subtitle id, and I think it's this one: https://www.opensubtitles.com/kr/subtitles/stargate-atlantis-5x20-enemy-at-the-gate-hdtv-aaf

I don't have anything from that show so it shouldn't try to download that subtitle to begin with.
I'm not sure if it's relevant but I do have a Frasier episode with the same title. That said, removing that episode did not solve the problem. Nor did removing and re-installing the plugin.

**Comment by MBR-0001** [comment]
That happens sometimes, there's really nothing that the plugin can do, the subtitle is simply broken on their (opensubtitles) side. It's worth mentioning that it doesn't affect the task.

I've checked just now, the API returns `Love Actually.srt` for that ID but attempting to download it results in an error response.

**Comment by MBR-0001** [comment]
@earder just fyi, the problem has been solved on their side (for this specific file)

**Comment by earder** [comment]
Thank you for your help and explanation. Much appreciated!

**Comment by earder** [comment]
Not an issue within the plugin. Solved at opensubtitles.com.
