### ISSUE TITLE
Keyboard not showing and can't login

### ISSUE THREAD

**Issue by dausruddin** [jellyfin/jellyfin-plugin-opensubtitles#18]
On my Android browser, I think I have 2 issue here.

1. [Keyboard not showing](https://i.imgur.com/lqRAjBw.jpg) 
    I had to type credentials somewhere and copy then paste it in the box.

2. [Can't login](https://i.imgur.com/8zncwww.jpg) 
    After hitting the login button button, it went to infinite loading. This is the log
```
[2019-11-06 08:54:26.882 +08:00] [ERR] Error processing request
System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)
   at System.Guid.TryParseGuidWithNoStyle(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidStyles flags, GuidResult& result)
   at System.Guid..ctor(String g)
   at MediaBrowser.Api.PluginService.Post(UpdatePluginConfiguration request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by dausruddin** [comment]
This is my first usage of the plugin. So I don't know if it was working on previous version of Jellyfin or not

**Comment by dausruddin** [comment]
Suddenly now keyboard is showing up. But still I cannot login due to issue described above.

**Comment by funtastix** [comment]
Had a similar issue with Savin various settings, especially for plugins. I think this must be related to parsing urls and the new baseurl. I worked around this by removing the baseurl in networking.

**Comment by dausruddin** [comment]
@funtastix yep, sometimes in login page too. I haven't try removing baseurl yet because it might break things on users using my server.

**Comment by dausruddin** [comment]
Is this related to the jellyfin core itself? Should I open an issue in main repo?

**Comment by Bond-009** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin/pull/2008
