### ISSUE TITLE
Plugin doesn't find any subtitles

### ISSUE THREAD

**Issue by Vetuska** [jellyfin/jellyfin-plugin-opensubtitles#22]
Jellyfin cannot find any subtitles. Getting these error messages. Searched through all .xml files in filesystem and they seemed OK!

```
[2019-12-19 21:12:10.046 +02:00] [ERR] Error downloading subtitles from "Open Subtitles"
System.Xml.XmlException: Unexpected XML declaration. The XML declaration must be the first node in the document, and no whitespace characters are allowed to appear before it. Line 1, position 4.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParsePI(StringBuilder piInDtdStringBuilder)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at XmlRpcHandler.XmlRpcGenerator.DecodeMethodResponse(String xmlResponse)
   at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
```

```
[2019-12-19 21:18:21.444 +02:00] [ERR] Error downloading subtitles from "Open Subtitles"
System.Xml.XmlException: Unexpected XML declaration. The XML declaration must be the first node in the document, and no whitespace characters are allowed to appear before it. Line 1, position 4.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParsePI(StringBuilder piInDtdStringBuilder)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at XmlRpcHandler.XmlRpcGenerator.DecodeMethodResponse(String xmlResponse)
   at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()
```

Jellyfin version: 10.4.1
Open subtitles plugin version: 7.0.0.0

**Comment by Vetuska** [comment]
Updated jellyfin to Version: 10.4.3 with latest Open subtitles plugin version: 7.0.0.0.
Same result. Even made new account to opensubtitles for testing. Can't find any subtitles.

![image](https://user-images.githubusercontent.com/59065425/71639921-36d08b80-2c89-11ea-8b79-1bd1f1f5de6e.png)

**Comment by cvium** [comment]
Can you include the XML?

**Comment by Vetuska** [comment]
> Can you include the XML?

Thank you for you reply,

I have no idea what is the .xml file what error is referring to. I searched my filesystem for all .xml files and looked into them and all seemed fine to me. I also deleted all .xml which referred to subtitles and system re-maked them and still getting the same error.

**Comment by Vetuska** [comment]
Is there any way I could find out what is the .xml which error is referring? I already set the logging.json to "MinimumLevel": "Debug". Not giving any extra information.

**Comment by AlexandreBonneau** [comment]
For info Jellyfin `10.7.0-1` also has this bug while the previous version 10.6.? did not.
