### ISSUE TITLE
Opensubtitles Rate Limit Exceeded

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-plugin-opensubtitles#28]
Opensubtitles will exceed the rate limit of the API. 

https://trac.opensubtitles.org/projects/opensubtitles/wiki/XMLRPC
`API Request limit: 40 HTTP requests per 10 seconds per IP address`

We should also probably integrate the X-ratelimit header to the sources that respect the header. 
`Check HTTP Response header 'X-RateLimit-Remaining' for http requests remaining per given period. `

Might be worth while for this as well
`If you get 407 Download limit reached, do not use persistent connections (HTTP keep-alive) and don't download more than 200 subtitles per 24 hour per IP/User `

Paid members still have a rate limit
`Higher download limits - 1000 subtitles/24 hours - useful when using programs such as media centers (but no abusing!)`

**Comment by JustAMan** [comment]
This feels like the Opensubtitles plugin issue, so I moved it.

**Comment by develroo** [comment]
I can confirm that the rate limit does seem to be reset after 24 hours so scheduling it to run every 48 hours means I get at least another 200 subtitles but really it makes my logs a mess with messages like this. 
```

MediaBrowser.Model.Net.HttpException: Too Many Requests
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at OpenSubtitlesHandler.Utilities.SendRequestAsync(Byte[] request, String userAgent, CancellationToken cancellationToken)
   at OpenSubtitlesHandler.OpenSubtitles.SearchSubtitlesAsync(SubtitleSearchParameters[] parameters, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[04:00:35] [ERR] Error downloading subtitles from Open Subtitles

```

**Comment by dkanada** [comment]
We should probably stop a scan with no account when this result is returned.
