### ISSUE TITLE
Windows 10 - Opensubtitles plugin not working when placed in plugins directory

### ISSUE THREAD

**Issue by o75steve** [jellyfin/jellyfin-plugin-opensubtitles#40]
Hi,
Installing opensubtitles plugin doesn't work. 

1. Installing from the catalog in Jellyfin does not work, it hangs up indefinitely then. 
Error message I get in that case is : 

[21:04:54] [ERR] [9] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://localhost:8097/Packages/Installed/Open Subtitles?AssemblyGuid=4b9ed42f-5185-48b5-9803-6ff2989014c4&version=10.0.0.0
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Open Subtitles
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

2. I've tried manually installed the opensubtitles plugin by cloning and building the repository, and then placing the resulting bin folder in my plugins directory. 
However, when restarting jellyfin I get the error messages like below, and jellyfin exits.
After removing the bin folder, every works fine again. 

21:01:39] [INF] [1] Main: Jellyfin version: 10.6.4
[21:01:39] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\\ProgramData\\Jellyfin\\Server\\log]"]
[21:01:39] [INF] [1] Main: Arguments: ["C:\\Program Files\\Jellyfin\\Server\\jellyfin.dll", "--datadir", "C:\\ProgramData\\Jellyfin\\Server"]
[21:01:39] [INF] [1] Main: Operating system: Windows
[21:01:39] [INF] [1] Main: Architecture: X64
[21:01:39] [INF] [1] Main: 64-Bit Process: True
[21:01:39] [INF] [1] Main: User Interactive: True
[21:01:39] [INF] [1] Main: Processor count: 12
[21:01:39] [INF] [1] Main: Program data path: C:\ProgramData\Jellyfin\Server
[21:01:39] [INF] [1] Main: Web resources path: C:\Program Files\Jellyfin\Server\jellyfin-web
[21:01:39] [INF] [1] Main: Application directory: C:\Program Files\Jellyfin\Server\
[21:01:39] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: C:\ProgramData\Jellyfin\Server\cache
[21:01:39] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[21:01:39] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Failed to load assembly C:\ProgramData\Jellyfin\Server\plugins\bin\Jellyfin.Data.dll
System.IO.FileLoadException: Could not load file or assembly 'Jellyfin.Data, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
[21:01:39] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from C:\ProgramData\Jellyfin\Server\plugins\bin\Jellyfin.Plugin.OpenSubtitles.dll
[21:01:39] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error getting exported types from Jellyfin.Plugin.OpenSubtitles, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()

[21:01:39] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Failed to load assembly C:\ProgramData\Jellyfin\Server\plugins\bin\MediaBrowser.Common.dll
System.IO.FileLoadException: Could not load file or assembly 'MediaBrowser.Common, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
[21:01:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Failed to load assembly C:\ProgramData\Jellyfin\Server\plugins\bin\MediaBrowser.Controller.dll
System.IO.FileLoadException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
[21:01:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Failed to load assembly C:\ProgramData\Jellyfin\Server\plugins\bin\MediaBrowser.Model.dll
System.IO.FileLoadException: Could not load file or assembly 'MediaBrowser.Model, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
[21:01:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly Microsoft.AspNetCore.Http.Abstractions, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 from C:\ProgramData\Jellyfin\Server\plugins\bin\Microsoft.AspNetCore.Http.Abstractions.dll
[21:01:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly Microsoft.AspNetCore.Http.Features, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 from C:\ProgramData\Jellyfin\Server\plugins\bin\Microsoft.AspNetCore.Http.Features.dll
[21:01:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Failed to load assembly C:\ProgramData\Jellyfin\Server\plugins\bin\Microsoft.Data.Sqlite.dll
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Data.Sqlite, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
[21:01:40] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly Microsoft.DotNet.PlatformAbstractions, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 from C:\ProgramData\Jellyfin\Server\plugins\bin\Microsoft.DotNet.PlatformAbstractions.dll
[21:01:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Failed to load assembly C:\ProgramData\Jellyfin\Server\plugins\bin\Microsoft.EntityFrameworkCore.Abstractions.dll
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Abstractions, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
[21:01:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Failed to load assembly C:\ProgramData\Jellyfin\Server\plugins\bin\Microsoft.EntityFrameworkCore.dll
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
[21:01:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Failed to load assembly C:\ProgramData\Jellyfin\Server\plugins\bin\Microsoft.EntityFrameworkCore.Relational.dll
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
[21:01:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Failed to load assembly C:\ProgramData\Jellyfin\Server\plugins\bin\Microsoft.EntityFrameworkCore.Sqlite.dll
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Sqlite, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
[21:01:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Failed to load assembly C:\ProgramData\Jellyfin\Server\plugins\bin\Microsoft.Extensions.Caching.Abstractions.dll
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Caching.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
[21:01:40] [ERR

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin/issues/5129
Install a lower version.

**Comment by o75steve** [comment]
ok thanks that did it
