### ISSUE TITLE
NullReferenceException raised with the latest build

### ISSUE THREAD

**Issue by Nehereus** [jellyfin/jellyfin-plugin-opensubtitles#53]
**Describe the issue**
I build the plugin from the repo and placed the DLL files generated in the plugin directory. After I log in from the configuration panel and try to search subtitles for a movie, the plugin failed to work

**System:**

OS: Debian
Jellyfin Version: 10.7.1
Open Subtitles plugin version: build from source

**Logs**
```
[ERR] Error downloading subtitles from "Open Subtitles"
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenSubtitlesHandler.Utilities.SendRequestAsync(Byte[] request, String userAgent, CancellationToken cancellationToken)
   at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()
```

**Comment by Nehereus** [comment]
similar to #15
