### ISSUE TITLE
MediaBrowser.Model.Net.HttpException: Misused header name.

### ISSUE THREAD

**Issue by wiwie** [jellyfin/jellyfin-plugin-opensubtitles#7]
I keep getting the following error in my log:

> [17:50:02] [ERR] Error downloading subtitles from Open Subtitles
> MediaBrowser.Model.Net.HttpException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
>    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
>    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
>    at OpenSubtitlesHandler.Utilities.SendRequestAsync(Byte[] request, String userAgent, CancellationToken cancellationToken)
>    at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String userName, String password, String language, CancellationToken cancellationToken)
>    at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
>    at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
>

**Comment by yfdoor** [comment]
same issue,
`[2019-07-21 15:32:31.032 +08:00] [ERR] Error downloading subtitles from "Open Subtitles"
System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_EnableHttpCompression(Boolean)'.
   at OpenSubtitlesHandler.Utilities.SendRequestAsync(Byte[] request, String userAgent, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at OpenSubtitlesHandler.Utilities.SendRequestAsync(Byte[] request, String userAgent, CancellationToken cancellationToken)
   at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)`

**Comment by anthonylavado** [comment]
Hi all, this was reported in #8, and is fixed in #9. It will be part of the next version, 4.0.0.0, which is yet to be released.

**Comment by yfdoor** [comment]
> Hi all, this was reported in #8, and is fixed in #9. It will be part of the next version, 4.0.0.0, which is yet to be released.

could you pls let us know when we can get this new releaae? thx
