### ISSUE TITLE
not working due to Json error

### ISSUE THREAD

**Issue by hookery** [jellyfin/jellyfin-plugin-opensubtitles#72]
I have added open subtitles plugin , and it worked like this
![1634798306(1)](https://user-images.githubusercontent.com/49587654/138224666-30f4ad4a-8354-49aa-8160-ee3e5202dc6f.png)

However, when i play the vedio, it didn't work, and the log show as below.
---------------------------------------------------------------------------------------------------
[2021-10-21 13:38:07.483 +08:00] [ERR] [60] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from "Open Subtitles"
System.Text.Json.JsonException: Failed to parse response, code: Moved, context: options: System.Collections.Generic.Dictionary`2[System.String,System.String], page: 1, body: 
""
 ---> System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at OpenSubtitlesHandler.Models.ApiResponse`1..ctor(HttpResponse response, String[] context)
   --- End of inner exception stack trace ---
   at OpenSubtitlesHandler.Models.ApiResponse`1..ctor(HttpResponse response, String[] context)
   at OpenSubtitlesHandler.OpenSubtitles.SearchSubtitlesAsync(Dictionary`2 options, String apiKey, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)

-------------------------------------------------------------------------------------------------------

And it repeate this error once and once again. It seems the data about movie sent/recevie to/from server is not json format or not valid. Does some know this issue? I don't know how this plugin search the subtitles,  which information it used. Does anyone know? Maybe i should change the movie's metadata or other things?

**Comment by MBR-0001** [comment]
Opensubtitles is currently upgrading their systems ([status page](https://92500a62-df9e-42ed-82a4-e6b3eeb89365.site.hbuptime.com/)) so the plugin wont work fully/at all
