### ISSUE TITLE
System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by whity** [jellyfin/jellyfin-plugin-opensubtitles#8]
Hello,

I'm getting the following error from the plugin:

`System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_EnableHttpCompression(Boolean)'.
   at OpenSubtitlesHandler.Utilities.SendRequestAsync(Byte[] request, String userAgent, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at OpenSubtitlesHandler.Utilities.SendRequestAsync(Byte[] request, String userAgent, CancellationToken cancellationToken)
   at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()`

Thanks.

**Comment by whity** [comment]
Thanks for the quick fix.

**Comment by anthonylavado** [comment]
@whity Thanks to @flyer280 :)

We still have to re-release the plugin at this point, so hold tight.

**Comment by ToXinE** [comment]
It's still an issue in 3.0.0.0 version.

**Comment by anthonylavado** [comment]
@ToXinE - That's right, it is fixed in the still unreleased 4.0.0.0 version. Once we've got that out, it'll be okay :-)

**Comment by balasankarc** [comment]
@anthonylavado Thanks for the fix.

Any ETA on the release of 4.0.0.0? Or even better - any hints on how one can build the plugin and install it manually? :)
